behaviors:
  AGVAgent:
    trainer_type: ppo
    time_horizon: 128
    max_steps: 2.0e6
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 100000
    threaded: true

    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 2.0e-4
      beta: 1.0e-3
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
